import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { Router, NavigationStart, NavigationEnd, NavigationCancel, NavigationError } from '@angular/router';
import { addIcons } from 'ionicons';
import { ThemeService } from './services/theme.service';
import { LoadingService } from './services/loading.service';
import {
  add,
  addCircleOutline,
  addOutline,
  alertCircleOutline,
  arrowBackOutline,
  arrowDown,
  arrowForwardOutline,
  bulb,
  calendarOutline,
  carOutline,
  cartOutline,
  chatbubbleEllipsesOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  checkmarkDoneOutline,
  checkmarkOutline,
  chevronForward,
  close,
  closeOutline,
  cloudUploadOutline,
  copyOutline,
  createOutline,
  cubeOutline,
  documentTextOutline,
  downloadOutline,
  eyeOffOutline,
  eyeOutline,
  flashOutline,
  homeOutline,
  hourglassOutline,
  informationCircleOutline,
  keyOutline,
  listOutline,
  locate,
  locationOutline,
  lockClosedOutline,
  logOutOutline,
  mailOutline,
  map,
  mapOutline,
  moon,
  navigateOutline,
  notificationsOffOutline,
  notificationsOutline,
  peopleOutline,
  person,
  personAddOutline,
  personCircleOutline,
  personOutline,
  printOutline,
  refreshOutline,
  searchOutline,
  send,
  shieldCheckmarkOutline,
  sunny,
  timeOutline,
  trashOutline,
  shareOutline,
  pricetagOutline,
  barbellOutline,
  layersOutline,
  businessOutline,
  chevronDownOutline,
  documentText,
  pencilOutline,
  swapHorizontalOutline,
  chatbubbleEllipses,
  warningOutline
} from 'ionicons/icons';

import { LoadingSplashComponent } from './components/loading-splash/loading-splash.component';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor(
    private themeService: ThemeService,
    private router: Router,
    private loadingService: LoadingService
  ) {
    /**
     * Registering icons for Standalone mode.
     * This resolves the [Ionicons Warning] in your console.
     */
    addIcons({
      'add': add,
      'add-circle-outline': addCircleOutline,
      'add-outline': addOutline,
      'alert-circle-outline': alertCircleOutline,
      'arrow-back-outline': arrowBackOutline,
      'arrow-down': arrowDown,
      'arrow-forward-outline': arrowForwardOutline,
      'bulb': bulb,
      'calendar-outline': calendarOutline,
      'car-outline': carOutline,
      'cart-outline': cartOutline,
      'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
      'checkmark-circle': checkmarkCircle,
      'checkmark-circle-outline': checkmarkCircleOutline,
      'checkmark-done-outline': checkmarkDoneOutline,
      'checkmark-outline': checkmarkOutline,
      'chevron-forward': chevronForward,
      'close': close,
      'close-outline': closeOutline,
      'cloud-upload-outline': cloudUploadOutline,
      'copy-outline': copyOutline,
      'create-outline': createOutline,
      'cube-outline': cubeOutline,
      'document-text-outline': documentTextOutline,
      'download-outline': downloadOutline,
      'eye-off-outline': eyeOffOutline,
      'eye-outline': eyeOutline,
      'flash-outline': flashOutline,
      'home-outline': homeOutline,
      'hourglass-outline': hourglassOutline,
      'information-circle-outline': informationCircleOutline,
      'key-outline': keyOutline,
      'list-outline': listOutline,
      'locate': locate,
      'location-outline': locationOutline,
      'lock-closed-outline': lockClosedOutline,
      'log-out-outline': logOutOutline,
      'mail-outline': mailOutline,
      'map': map,
      'map-outline': mapOutline,
      'moon': moon,
      'navigate-outline': navigateOutline,
      'notifications-off-outline': notificationsOffOutline,
      'notifications-outline': notificationsOutline,
      'people-outline': peopleOutline,
      'person': person,
      'person-add-outline': personAddOutline,
      'person-circle-outline': personCircleOutline,
      'person-outline': personOutline,
      'print-outline': printOutline,
      'refresh-outline': refreshOutline,
      'search-outline': searchOutline,
      'send': send,
      'shield-checkmark-outline': shieldCheckmarkOutline,
      'sunny': sunny,
      'time-outline': timeOutline,
      'trash-outline': trashOutline,
      'warning-outline': warningOutline,
      'share-outline': shareOutline,
      'pricetag-outline': pricetagOutline,
      'barbell-outline': barbellOutline,
      'layers-outline': layersOutline,
      'business-outline': businessOutline,
      'chevron-down-outline': chevronDownOutline,
      'document-text': documentText,
      'pencil-outline': pencilOutline,
      'swap-horizontal-outline': swapHorizontalOutline,
      'chatbubble-ellipses': chatbubbleEllipses
    });

    this.loadingService.hide();
  }
}